name: Publish to NPM

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: NPM Install
        run: npm install
      - name: Upgrade Package version"
        run: node dxbpackagecalc.js
      - name: NPM Publish DXB
        run: npm publish
      - name: Commit report
        run: |
          git config --global user.name 'David Browaeys'
          git config --global user.email 'david.browaeys@gmail.com'
          git add 'package.json'
          git commit -am "DXB Auto Update package version"
          git push